INSERT INTO USER_TABLE (ID, USER_LOGIN, FULLNAME, SECOND_NAME, COUNTRY, CITY, POINTS)
VALUES (user_seq.nextval, 'armn', 'NeilArmstrong','SECOND NAME','XD','xd',10);
INSERT INTO QUEST (ID, FULLNAME, CITY, STATUS, USER_ID)
VALUES (quest_seq.nextval, 'aadam','xd','COMPLETED',1);

