GET http://localhost:8080/users

<> 2020-06-17T025249.200.json

###

GET http://localhost:8080/quests

<> 2020-06-17T025249.200.json

###

POST http://localhost:8080/quests
Content-Type: application/json

{"name": "jebacandrzejaa", "city": "Andrazej", "status": "COMPLETED", "user": {"id": 1}}

<> 2020-06-08T024508.404.json

###

POST http://localhost:8080/users
Content-Type: application/json

{"login": "Andrzej1", "name": "Andrzej1", "nazwisko": "Du1da", "country": "XD1D", "city": "XDDD1","points": 10}

<> 2020-06-08T024508.404.json
